```{r}
library(SummarizedExperiment, quietly=T)
library(dplyr)
library(readr)
library(tibble)
library(GenomicRanges)

```

```{r}
counts <- read.csv("HEPG2_count_file.tsv", sep="\t")
column_data <- read.csv("column_data_HEPG2.tsv", sep="\t")

column_data <- column_data[ order(match(column_data$Experiment.accession, colnames(counts))), ]
rownames(column_data) <- NULL

row_data <- read.csv("../rowdata.tsv", sep="\t")
```

```{r}
column_data <- column_to_rownames(column_data, "Experiment.accession")
counts <- column_to_rownames(counts, "Gene.id")
row_data <- column_to_rownames(row_data, "Gene_id")
se <- SummarizedExperiment(assays = list(counts = data.matrix(counts)), colData = column_data, rowData=row_data)

save(se, file = "se_HEPG2.rda")
```

Filtering se
```{r}
#Filtering number of counts for each row if necessary
rowTotal = 0
keep <- rowSums(assay(se)) > 0
se <- se[keep,]

#Filtering gene types if necessary
#Finding gene types
gene_type <- as.data.frame(se@elementMetadata@listData$Gene_type)
colnames(gene_type) <- c("GENETYPE")
gene_type <- as.data.frame(count(gene_type, GENETYPE))
gene_type <- gene_type[order(-gene_type$n),]

#IF we want to select certain gene types
wantedGenes <- c('protein_coding',"lncRNA")
keep2 <- se@elementMetadata@listData$Gene_type ==  wantedGenes 
se2 <- se[keep2,]
save(se2, file = "se2_HEPG2.rda")

```


```{r}
rowData(se)
colData(se)
assay(se)
```





















