---
title: "code_for_pca_and_kmeans"
date: "`r Sys.Date()`"
output: html_document
---

PCA
```{r setup, include=FALSE}
### One way to do it:
se.pca <- prcomp(assay(se))
se.pca.var <- se.pca$sdev^2
se.pca.var.prop <- se.pca.var / sum(se.pca.var)
plot(se.pca.var.prop, xlab = "Principal Component",
                      ylab = "Proportion of Variance Explained",
                      type = "b")
se.PC1PC2 <- se.pca$x[,1:2]
plot(se.PC1PC2)

### Another way:
#install.packages("devtools")
#install_github("vqv/ggbiplot")
library(devtools)
library(ggbiplot)
se.pca <- prcomp(assay(se), center=TRUE, scale=TRUE)
ggbiplot(se.pca)
```

K-means
``` {r}
# elbow plot (to find the optimal number of clusters)
k.max <- 15
data <- assay(se)
wss <- sapply(1:k.max, 
              function(k){kmeans(data, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

# running kmeans and plotting results
#install.packages("factoextra")
library(factoextra)
res.km <- kmeans(assay(se), centers=5)
fviz_cluster(res.km, data = assay(se),
             palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#E7B750", "#E7B700"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
```